// Datos Mock para desarrollo sin backend
// Este archivo proporciona datos de ejemplo para todas las secciones del sistema

export const mockData = {
  // COLABORADORES
  colaboradores: [
    {
      id: 1,
      nombre: 'Juan Pérez',
      email: 'juan.perez@empresa.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=juan',
      departamento: 'Ingeniería',
      puesto: 'Senior Developer',
      nivelSeniority: 'Senior',
      fechaIngreso: '2020-01-15',
      puntos: 2350,
      nivel: 5,
      estado: 'Activo',
    },
    {
      id: 2,
      nombre: 'María García',
      email: 'maria.garcia@empresa.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=maria',
      departamento: 'Recursos Humanos',
      puesto: 'HR Manager',
      nivelSeniority: 'Senior',
      fechaIngreso: '2019-06-10',
      puntos: 1850,
      nivel: 4,
      estado: 'Activo',
    },
    {
      id: 3,
      nombre: 'Carlos López',
      email: 'carlos.lopez@empresa.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=carlos',
      departamento: 'Ingeniería',
      puesto: 'Junior Developer',
      nivelSeniority: 'Junior',
      fechaIngreso: '2023-03-20',
      puntos: 450,
      nivel: 1,
      estado: 'Activo',
    },
    {
      id: 4,
      nombre: 'Ana Rodríguez',
      email: 'ana.rodriguez@empresa.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ana',
      departamento: 'Ventas',
      puesto: 'Sales Manager',
      nivelSeniority: 'Senior',
      fechaIngreso: '2021-09-15',
      puntos: 1650,
      nivel: 3,
      estado: 'Activo',
    },
  ],

  // CURSOS
  cursos: [
    {
      id: 1,
      titulo: 'Vue.js Avanzado',
      descripcion: 'Domina los conceptos avanzados de Vue.js 3',
      categoria: 'Tecnología',
      duracion: 40,
      nivel: 'Avanzado',
      instructor: 'Dr. Miguel Torres',
      fechaInicio: '2024-12-01',
      fechaFin: '2024-12-31',
      cupos: 30,
      inscritos: 25,
      imagen: 'https://via.placeholder.com/300x200?text=Vue.js',
      estado: 'Activo',
    },
    {
      id: 2,
      titulo: 'Liderazgo Efectivo',
      descripcion: 'Desarrolla habilidades de liderazgo para equipos de alto desempeño',
      categoria: 'Desarrollo Profesional',
      duracion: 30,
      nivel: 'Intermedio',
      instructor: 'Lic. Patricia Mendez',
      fechaInicio: '2024-12-05',
      fechaFin: '2025-01-15',
      cupos: 25,
      inscritos: 20,
      imagen: 'https://via.placeholder.com/300x200?text=Liderazgo',
      estado: 'Activo',
    },
    {
      id: 3,
      titulo: 'TypeScript Fundamentals',
      descripcion: 'Aprende TypeScript desde cero',
      categoria: 'Tecnología',
      duracion: 25,
      nivel: 'Básico',
      instructor: 'Eng. Roberto Silva',
      fechaInicio: '2024-12-10',
      fechaFin: '2024-12-30',
      cupos: 40,
      inscritos: 35,
      imagen: 'https://via.placeholder.com/300x200?text=TypeScript',
      estado: 'Activo',
    },
    {
      id: 4,
      titulo: 'Comunicación Asertiva',
      descripcion: 'Mejora tu comunicación en el trabajo',
      categoria: 'Habilidades Blandas',
      duracion: 20,
      nivel: 'Básico',
      instructor: 'Psic. Laura Fernández',
      fechaInicio: '2024-12-15',
      fechaFin: '2025-01-10',
      cupos: 50,
      inscritos: 45,
      imagen: 'https://via.placeholder.com/300x200?text=Comunicacion',
      estado: 'Activo',
    },
    {
      id: 5,
      titulo: 'React Hooks Avanzado',
      descripcion: 'Domina React Hooks y el rendering condicional',
      categoria: 'Tecnología',
      duracion: 35,
      nivel: 'Avanzado',
      instructor: 'Dev. Alexander López',
      fechaInicio: '2024-12-20',
      fechaFin: '2025-01-30',
      cupos: 20,
      inscritos: 18,
      imagen: 'https://via.placeholder.com/300x200?text=React',
      estado: 'Activo',
    },
  ],

  // PROGRESS DE CURSOS POR USUARIO
  cursoProgress: [
    {
      id: 1,
      colaboradorId: 1,
      cursoId: 1,
      estado: 'En Progreso',
      porcentaje: 75,
      fechaInscripcion: '2024-11-15',
      ultimaActividad: '2024-11-27',
      modulos: [
        { titulo: 'Introducción', completado: true },
        { titulo: 'Componentes Avanzados', completado: true },
        { titulo: 'State Management', completado: true },
        { titulo: 'Testing', completado: false },
      ],
    },
    {
      id: 2,
      colaboradorId: 1,
      cursoId: 2,
      estado: 'Completado',
      porcentaje: 100,
      fechaInscripcion: '2024-10-01',
      fechaCompletacion: '2024-11-20',
      calificacion: 95,
      certificado: true,
    },
    {
      id: 3,
      colaboradorId: 2,
      cursoId: 1,
      estado: 'En Progreso',
      porcentaje: 45,
      fechaInscripcion: '2024-11-10',
      ultimaActividad: '2024-11-26',
    },
    {
      id: 4,
      colaboradorId: 3,
      cursoId: 3,
      estado: 'En Progreso',
      porcentaje: 20,
      fechaInscripcion: '2024-11-20',
      ultimaActividad: '2024-11-27',
    },
  ],

  // VACANTES
  vacantes: [
    {
      id: 1,
      titulo: 'Senior Full Stack Developer',
      descripcion:
        'Buscamos un desarrollador full stack senior con experiencia en Vue.js y Node.js',
      departamento: 'Ingeniería',
      salario: '$8000 - $12000',
      ubicacion: 'Remoto',
      tipoContrato: 'Indefinido',
      experienciaRequerida: 5,
      estado: 'Abierta',
      fechaPublicacion: '2024-11-01',
      deadline: '2024-12-31',
      listaRequisitos: ['Vue.js 3', 'Node.js/Express', 'SQL', 'JavaScript/TypeScript', 'Git'],
      skillsRequeridos: ['Vue.js', 'Node.js', 'JavaScript', 'SQL', 'REST APIs'],
      candidatos: 12,
    },
    {
      id: 2,
      titulo: 'Product Manager',
      descripcion: 'Gestiona el desarrollo de nuevos productos digitales',
      departamento: 'Producto',
      salario: '$6000 - $9000',
      ubicacion: 'Oficina Principal',
      tipoContrato: 'Indefinido',
      experienciaRequerida: 3,
      estado: 'Abierta',
      fechaPublicacion: '2024-11-10',
      deadline: '2024-12-20',
      listaRequisitos: ['Product Management', 'Agile', 'Análisis de datos', 'Liderazgo'],
      skillsRequeridos: ['Product Strategy', 'Analytics', 'Leadership'],
      candidatos: 8,
    },
    {
      id: 3,
      titulo: 'QA Engineer',
      descripcion: 'Asegura la calidad de nuestros productos',
      departamento: 'Calidad',
      salario: '$4000 - $6000',
      ubicacion: 'Híbrido',
      tipoContrato: 'Indefinido',
      experienciaRequerida: 2,
      estado: 'Abierta',
      fechaPublicacion: '2024-11-15',
      deadline: '2024-12-15',
      listaRequisitos: ['Testing', 'Automatización', 'SQL', 'JavaScript'],
      skillsRequeridos: ['QA Testing', 'Selenium', 'Jest', 'SQL'],
      candidatos: 15,
    },
  ],

  // SKILLS
  skills: [
    {
      id: 1,
      nombre: 'Vue.js',
      categoria: 'Frontend',
      nivel: 'Avanzado',
      descripcion: 'Framework de JavaScript para construir interfaces',
    },
    {
      id: 2,
      nombre: 'Node.js',
      categoria: 'Backend',
      nivel: 'Avanzado',
      descripcion: 'Runtime de JavaScript en el servidor',
    },
    {
      id: 3,
      nombre: 'TypeScript',
      categoria: 'Lenguajes',
      nivel: 'Intermedio',
      descripcion: 'Lenguaje tipado basado en JavaScript',
    },
    {
      id: 4,
      nombre: 'React',
      categoria: 'Frontend',
      nivel: 'Avanzado',
      descripcion: 'Librería para construir interfaces',
    },
    {
      id: 5,
      nombre: 'SQL',
      categoria: 'Bases de Datos',
      nivel: 'Intermedio',
      descripcion: 'Lenguaje de consultas de bases de datos',
    },
    {
      id: 6,
      nombre: 'Liderazgo',
      categoria: 'Soft Skills',
      nivel: 'Intermedio',
      descripcion: 'Habilidad de liderazgo y gestión',
    },
    {
      id: 7,
      nombre: 'Comunicación',
      categoria: 'Soft Skills',
      nivel: 'Básico',
      descripcion: 'Comunicación efectiva',
    },
  ],

  // SKILLS POR COLABORADOR
  colaboradorSkills: [
    {
      colaboradorId: 1,
      skillId: 1,
      nivel: 'Avanzado',
      experiencia: 5,
    },
    {
      colaboradorId: 1,
      skillId: 2,
      nivel: 'Avanzado',
      experiencia: 4,
    },
    {
      colaboradorId: 1,
      skillId: 3,
      nivel: 'Intermedio',
      experiencia: 2,
    },
    {
      colaboradorId: 2,
      skillId: 6,
      nivel: 'Avanzado',
      experiencia: 6,
    },
    {
      colaboradorId: 2,
      skillId: 7,
      nivel: 'Avanzado',
      experiencia: 5,
    },
    {
      colaboradorId: 3,
      skillId: 1,
      nivel: 'Básico',
      experiencia: 1,
    },
    {
      colaboradorId: 3,
      skillId: 3,
      nivel: 'Intermedio',
      experiencia: 1,
    },
  ],

  // NOTIFICACIONES
  notificaciones: [
    {
      id: 1,
      colaboradorId: 1,
      tipo: 'curso',
      titulo: 'Nuevo curso disponible',
      mensaje: 'Vue.js Avanzado está disponible para inscripción',
      leida: false,
      fecha: '2024-11-27T10:30:00',
    },
    {
      id: 2,
      colaboradorId: 1,
      tipo: 'vacante',
      titulo: 'Nueva vacante en tu área',
      mensaje: 'Senior Full Stack Developer - Ingeniería',
      leida: false,
      fecha: '2024-11-27T09:15:00',
    },
    {
      id: 3,
      colaboradorId: 1,
      tipo: 'puntos',
      titulo: 'Felicidades',
      mensaje: 'Ganaste 100 puntos por completar un curso',
      leida: true,
      fecha: '2024-11-26T14:45:00',
    },
    {
      id: 4,
      colaboradorId: 2,
      tipo: 'deadline',
      titulo: 'Deadline próximo',
      mensaje: 'La vacante Senior Full Stack Developer cierra en 3 días',
      leida: false,
      fecha: '2024-11-27T08:00:00',
    },
  ],

  // REPORTES / ANALYTICS
  analytics: {
    kpis: [
      {
        id: 1,
        nombre: 'Colaboradores Activos',
        valor: 156,
        variacion: 5.2,
        tendencia: 'up',
      },
      {
        id: 2,
        nombre: 'Cursos Completados',
        valor: 342,
        variacion: 12.5,
        tendencia: 'up',
      },
      {
        id: 3,
        nombre: 'Skills Desarrolladas',
        valor: 89,
        variacion: -2.3,
        tendencia: 'down',
      },
      {
        id: 4,
        nombre: 'Tasa de Enganche',
        valor: '78%',
        variacion: 3.1,
        tendencia: 'up',
      },
    ],
    skillsInventario: [
      { skill: 'Vue.js', colaboradores: 34, nivel: 'Avanzado' },
      { skill: 'React', colaboradores: 45, nivel: 'Avanzado' },
      { skill: 'TypeScript', colaboradores: 28, nivel: 'Intermedio' },
      { skill: 'Node.js', colaboradores: 32, nivel: 'Avanzado' },
      { skill: 'SQL', colaboradores: 56, nivel: 'Intermedio' },
      { skill: 'Liderazgo', colaboradores: 45, nivel: 'Intermedio' },
      { skill: 'Comunicación', colaboradores: 98, nivel: 'Básico' },
    ],
  },

  // APLICACIONES A VACANTES
  aplicaciones: [
    {
      id: 1,
      vacanteId: 1,
      colaboradorId: 1,
      estado: 'Entrevista Programada',
      fechaSolicitud: '2024-11-20',
      fechaEntrevista: '2024-12-05',
      puntuacion: 85,
    },
    {
      id: 2,
      vacanteId: 1,
      colaboradorId: 2,
      estado: 'En Revisión',
      fechaSolicitud: '2024-11-22',
      puntuacion: 0,
    },
    {
      id: 3,
      vacanteId: 2,
      colaboradorId: 2,
      estado: 'Oferta Enviada',
      fechaSolicitud: '2024-11-18',
      puntuacion: 90,
    },
    {
      id: 4,
      vacanteId: 3,
      colaboradorId: 3,
      estado: 'En Revisión',
      fechaSolicitud: '2024-11-25',
      puntuacion: 0,
    },
  ],

  // BENEFICIOS
  beneficios: [
    {
      id: 1,
      nombre: 'Descuento en Gym',
      descripcion: '20% descuento en membresía de gimnasio',
      puntosRequeridos: 500,
      stock: 25,
    },
    {
      id: 2,
      nombre: 'Bono de Viaje',
      descripcion: 'Voucher de $500 para viajes',
      puntosRequeridos: 1000,
      stock: 10,
    },
    {
      id: 3,
      nombre: 'Certificación Gratuita',
      descripcion: 'Curso de certificación profesional',
      puntosRequeridos: 800,
      stock: 15,
    },
  ],

  // ENCUESTAS DE SALIDA
  encuestas: [
    {
      id: 1,
      titulo: 'Encuesta de Satisfacción',
      preguntas: [
        {
          id: 1,
          texto: '¿Cómo fue tu experiencia en la empresa?',
          tipo: 'escala',
        },
        {
          id: 2,
          texto: '¿Recomendarías a la empresa a otros?',
          tipo: 'si_no',
        },
        {
          id: 3,
          texto: 'Comentarios adicionales',
          tipo: 'texto',
        },
      ],
    },
  ],
}

export default mockData
